#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-1 eDP-1
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 
bspc monitor eDP-1 -d 8 9 

bspc config border_width         1
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#CBA6F7"
bspc config normal_border_color "#45475A"

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Gimp state=fullscreen
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
# bspc rule -a polybar state=floating layer=above

export PATH="$PATH:/usr/local/texlive/2025/bin/x86_64-linux:~/rofi-translate"

# Autostart apps
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/vjyjylarb9vf1.png &
$HOME/scripts/bspwm-padding-manager.sh &
dunst & 
polybar --config=$HOME/.config/polybar/config.ini &
emacs --daemon &
fcitx5 -d &
otd-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr
